# Generated by Django 5.2.14 on 2026-05-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='progress.activity'),
        ),
    ]
